const tintColorLight = '#19ff99';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    background: '#fff',
    badge: '#08f',
    badgeBackground: '#fff',
    icon: '#000'  ,
    tint: tintColorLight,
    tabIconDefault: '#c1ffcc',
    tabIconSelected: tintColorLight,
    placeholder: '#888',
    cursor: '#4e139c',
    underline: '#4e139c',
    borderColor: '#000',

  },
  dark: {
    text: '#fff',
    background: '#000',
    badge: '#08f',
    badgeBackground: '#fff',
    tint: tintColorDark,
    icon: '#fff'  ,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    placeholder: '#ccc',
    cursor: '#fff',
    underline: '#fff',
    borderColor: '#fff',
  },
  orange: {
    text: '#fff',
    background: '#fca103',
    badge: '#08f',
    badgeBackground: '#fff',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
  yellow: {
    text: '#fff',
    background: '#fcf803',
    badge: '#08f',
    badgeBackground: '#fff',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
  violet: {
    text: '#fff',
    background: '#670399',
    badge: '#08f',
    badgeBackground: '#fff',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
  blue: {
    text: '#fff',
    background: '#0f30d4',
    badge: '#08f',
    badgeBackground: '#fff',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
  green: {
    text: '#fff',
    background: '#0fd43d',
    badge: '#08f',
    badgeBackground: '#fff',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
  greenDark: {
    text: '#fff',
    background: '#1e7833',
    badge: '#08f',
    badgeBackground: '#fff',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
  blueDark: {
    text: '#fff',
    background: '#030b99',
    badge: '#08f',
    badgeBackground: '#fff',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
  pink: {
    text: '#fff',
    background: '#a705f7',
    badge: '#08f',
    badgeBackground: '#fff',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  }
};
